[package]
name = "lightarti-rest"
version = "0.3.2"
authors = ["Linus Gasser <linus.gasser@epfl.ch>",
    "Laurent Girod <laurent.girod@epfl.ch>",
    "Christian Grigis <christian.grigis@epfl.ch>",
    "Valérian Rousset <valerian.rousset@epfl.ch>"]
edition = "2018"

[lib]
name = "core"
crate-type = ["cdylib", "staticlib"]

[dependencies]
tor-bytes = { git = "https://github.com/c4dt/arti.git" }
tor-chanmgr = { git = "https://github.com/c4dt/arti.git" }
tor-circmgr = { git = "https://github.com/c4dt/arti.git" }
tor-config = { git = "https://github.com/c4dt/arti.git" }
tor-dirmgr = { git = "https://github.com/c4dt/arti.git" }
tor-proto = { git = "https://github.com/c4dt/arti.git" }
tor-rtcompat = { git = "https://github.com/c4dt/arti.git" }
anyhow = "1"
config = "0.11"
futures = "0.3"
http = "0.2"
httparse = "1"
log = "0.4"
log-panics = "2"
serde = { version = "1", features = ["derive"] }
tokio-native-tls = "0.3"
serde_json = "1.0.64"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-fmt = "0.1"
tracing-log = "0.1"

[dev-dependencies]
tempdir = "0.3"

[target.'cfg(target_os="android")'.dependencies]
jni = "0.19"
android_logger = "0.10"
tracing = { version = "0.1", features = ["log"] }

# needed to correctly link
openssl-sys = { version = "0.9", features = ["vendored"] }
rusqlite = { version = "0.25.1", features = ["bundled"] }

[target.'cfg(target_os = "ios")'.dependencies]
core-foundation = "0.9"
libc = "0.2"
url = "2.2.2"

[profile.release]
opt-level = "s" # reduce library size
lto = "fat" # use system linker (needed for iOS)
