[package]
name = "arti-rest"
version = "0.1.0"
authors = ["Linus Gasser <linus.gasser@epfl.ch>",
    "Laurent Girod <laurent.girod@epfl.ch>",
    "Christian Grigis <christian.grigis@epfl.ch>",
    "Valérian Rousset <valerian.rousset@epfl.ch>"]
edition = "2018"

[lib]
name = "core"
crate-type = ["cdylib", "staticlib"]

[dependencies]
log-panics = "2.0"
tracing = "0.1"
tracing-fmt = "0.1"
tracing-log = "0.1"

# Packages for tor
#tor-config = { git = "https://gitlab.torproject.org/tpo/core/arti.git", rev = "c372671b5ad2663151cbaf2ff392f1e6f0ba292f" }
#tor-chanmgr = { git = "https://gitlab.torproject.org/tpo/core/arti.git", rev = "c372671b5ad2663151cbaf2ff392f1e6f0ba292f" }
#tor-circmgr = { git = "https://gitlab.torproject.org/tpo/core/arti.git", rev = "c372671b5ad2663151cbaf2ff392f1e6f0ba292f" }
#tor-llcrypto = { git = "https://gitlab.torproject.org/tpo/core/arti.git", rev = "c372671b5ad2663151cbaf2ff392f1e6f0ba292f" }
#tor-proto = { git = "https://gitlab.torproject.org/tpo/core/arti.git", rev = "c372671b5ad2663151cbaf2ff392f1e6f0ba292f" }
#tor-rtcompat = { git = "https://gitlab.torproject.org/tpo/core/arti.git", rev = "c372671b5ad2663151cbaf2ff392f1e6f0ba292f" }

# Currently, we use a modified versionof Arti with a dummy consensus validation.
tor-config = { path="../arti/tor-config", version= "*" }
tor-chanmgr = { path="../arti/tor-chanmgr", version= "*", default-features=false }
tor-circmgr = { path="../arti/tor-circmgr", version= "*" }
tor-llcrypto = { path="../arti/tor-llcrypto", version= "*" }
tor-proto = { path="../arti/tor-proto", version= "*" }
tor-rtcompat = { path="../arti/tor-rtcompat", version= "*" }


tor-customdirmgr = { path = "./src/arti/tor-customdirmgr" }

async-std = { version = "1.9.0", features = ["attributes"] }
serde = { version = "1.0.124", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.6.7", features = ["full"] }
async-trait = "0.1.48"
chrono = "0.4.19"
futures = "0.3"
http = "0.2"
httparse = "1"
config = "0.11.0"
anyhow = "1.0.40"
tokio-rustls = "0.22"
webpki-roots = "0.21"
rand = "0.8.3"
ring = "0.16.19"
url = "2.2.2"

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.16", default-features = false }
android_logger = "0.10.1"
openssl-sys = { version = "0.9.62", features = ["vendored"] }
rusqlite = { version = "0.25.1", features = ["bundled"] }
tracing = {version = "0.1", features = ["log"] }

[target.'cfg(target_os = "ios")'.dependencies]
libc = "0.2"
core-foundation = "0.6.2"

[build-dependencies]
env_logger = "0.6"

[dev-dependencies]
tempdir = "0.3"

[profile.release]
lto = "fat"
opt-level = "s"
codegen-units = 1
panic = "abort"
