# List of Tor directory authorities and digests of their keys.
#
# Since Arti is currently client-only, there's no need to keep
# anything else about authorities (like addresses), since clients only
# connect to fallback directories.
#
# (List generated August 2020.)
#
# NOTE: This file is redundant; the real defaults are as listed in
# authority.rs.  Eventually we should remove this file, or
# somehow enforce that it matches authority.rs.

[[network.authority]]
name = "spring"
v3ident = "A1B62E1027298A07181BFEA6801360C21DDEDE51"
