name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Retrieve latest directory cache
        uses: dsaltares/fetch-gh-release-asset@0.0.5
        with:
          repo: c4dt/lightarti-directory
          version: latest
          file: directory-cache.tgz

      - name: Set up directory cache
        run: |
          mkdir ./directory-cache
          tar -C ./directory-cache -xf directory-cache.tgz

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
