name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-build-android-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-android

      - name: Run tests
        # Else the arti-sqlite might fail on concurrent access to the database
        run: cargo test -j 1
