name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Tor
        run: sudo apt-get install -y tor

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python dependencies
        working-directory: ./tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate authority and fresh dir info
        working-directory: ./tools
        env:
          DIR_AUTH_PASSWORD: dummy
        run: |
          make certificate
          make dirinfo

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test

  test-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest
        working-directory: ./tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run pytest
        working-directory: ./tools
        run: |
          python -m pytest
